# CI MODE - SIN BASE DE DATOS
spring.datasource.url=
spring.datasource.driver-class-name=
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

spring.jpa.hibernate.ddl-auto=none