# ==============================
# CONFIGURACIÓN GENERAL
# ==============================
spring.application.name=inkapark
server.port=8080

# ==============================
# BASE DE DATOS
# ==============================
spring.datasource.url=jdbc:mysql://localhost:3306/inkapark?useSSL=false&serverTimezone=America/Lima
spring.datasource.username=USUARIO_BASE_DATOS
spring.datasource.password=CONTRASENA_BASE_DATOS
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ==============================
# APLICACIÓN
# ==============================
app.base-url=http://localhost:8080
aforo.max=50

# ==============================
# CORREO SMTP
# ==============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=CORREO_GMAIL
spring.mail.password=CONTRASENA_DE_APLICACION
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8

logging.level.org.springframework.mail=INFO
app.contact.from-name=InkaPark