# ==============================
# 🟤 CONFIGURACIÓN GENERAL
# ==============================
spring.application.name=inkapark
server.port=8080

# ==============================
# 🟡 BASE DE DATOS MySQL
# ==============================
spring.datasource.url=jdbc:mysql://localhost:3306/inkapark?useSSL=false&serverTimezone=America/Lima
spring.datasource.username=inkapark
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ==============================
# 🟢 APLICACIÓN
# ==============================
# URL base que se usará para construir los enlaces de verificación
# (cámbiala si usas un dominio o puerto distinto)
app.base-url=http://localhost:8080

# Valor de ejemplo que ya tenías
aforo.max=50

# ==============================
# 🔵 CONFIGURACIÓN DE CORREO SMTP (Gmail)
# ==============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=inkaparka@gmail.com
spring.mail.password=jtkk vfwm cbfb mjuy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8

# (Opcional) mostrar logs del envío de correos en consola
logging.level.org.springframework.mail=INFO

app.contact.from-name=InkaPark
